name: Greet Everyone
on: 
  pull_request:
    paths:
      - 'plugins'

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Echo Greeting
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'