name: Pushed
on:
  push:
    paths:
      - 'plugins/*'

jobs:
  build:
    name: Push job
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: Upsert File
        uses: ./.github/actions/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_TOKEN: ${{ secrets.MY_TOKEN }}