name: Pushed
on:
  push:
    paths:
      - 'plugins/*'

jobs:
  build:
    name: Push job
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World
        uses: ./.github/actions/build
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Echo Greeting
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'