name: Pushed
on:
  push:
    paths:
      - 'plugins/*'

jobs:
  build:
    name: Push job
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Hello World
        uses: ./.github/actions/build
        id: hello