name: Pushed
on:
  push:
    paths:
      - 'plugins/*'

jobs:
  build:
    name: Push job
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World
        uses: ../actions/build
        id: hello